-- Tabelas de Escalas (UUID)

CREATE TABLE IF NOT EXISTS membros_escalas_eventos (
  id VARCHAR(36) NOT NULL PRIMARY KEY,
  pastoral_id VARCHAR(36) NOT NULL,
  titulo VARCHAR(140) NOT NULL,
  descricao TEXT NULL,
  data DATE NOT NULL,
  hora TIME NOT NULL,
  created_by VARCHAR(36) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_pastoral_data (pastoral_id, data)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS membros_escalas_funcoes (
  id VARCHAR(36) NOT NULL PRIMARY KEY,
  evento_id VARCHAR(36) NOT NULL,
  nome VARCHAR(100) NOT NULL,
  ordem INT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_evento (evento_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS membros_escalas_funcao_membros (
  id VARCHAR(36) NOT NULL PRIMARY KEY,
  funcao_id VARCHAR(36) NOT NULL,
  membro_id VARCHAR(36) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_funcao_membro (funcao_id, membro_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS membros_escalas_logs (
  id VARCHAR(36) NOT NULL PRIMARY KEY,
  evento_id VARCHAR(36) NULL,
  usuario_id VARCHAR(36) NULL,
  acao VARCHAR(60) NOT NULL,
  detalhes JSON NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


